routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\UserController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\CityController;
use App\Http\Controllers\FootballFieldController;
use App\Http\Controllers\FootballMatchController;
use App\Http\Controllers\LeagueController;
use App\Http\Controllers\LeagueTeamController;
use App\Http\Controllers\LeagueTeamPlayerController;
use App\Http\Controllers\LeagueRegisteredUserController;
use App\Http\Controllers\LeagueRegisteredGroupController;
use App\Http\Controllers\LeagueGroupController;
use App\Http\Controllers\LeagueGroupNameController;
use App\Http\Controllers\LeagueGroupTeamController;
use App\Http\Controllers\LeagueGroupTeamPlayerController;
use App\Http\Controllers\LeagueGroupRegisteredUserController;
use App\Http\Controllers\LeagueGroupRegisteredGroupController;
use App\Http\Controllers\LeagueMatchScheduleController;
use App\Http\Controllers\LeagueMatchPointController;
<<<<<<< HEAD
use App\Http\Controllers\ApplicationController;

=======
use App\Http\Controllers\LeagueGroupMatchScheduleController;
use App\Http\Controllers\LeagueGroupMatchPointController;
use App\Http\Controllers\GroupUserController;
use App\Http\Controllers\GroupController;
>>>>>>> f14405817e86cad95dce38ffcee9e2435b951a9d
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('welcome');
});
Auth::routes();
Route::resource('contacts', 'App\Http\Controllers\ContactController');
Route::resource('products', ProductController::class);
Route::resource('countries', CountryController::class);
Route::resource('cities', CityController::class);
Route::resource('footballFields', FootballFieldController::class);
Route::resource('footballMatches', FootballMatchController::class);
Route::resource('leagues', LeagueController::class);
//additional routes for leagues
Route::get('/leagues/createTeam/{id}', [LeagueController::class, 'createTeam'])->name('leagues.createTeam');
Route::get('/leagues/showFinancial/{league}', [LeagueController::class, 'showFinancial'])->name('leagues.showFinancial');
Route::get('/leagues/createMatches/{league}', [LeagueController::class, 'createMatches'])->name('leagues.createMatches');
Route::get('/leagues/matchesSchedule/{league}', [LeagueController::class, 'matchesSchedule'])->name('leagues.matchesSchedule');
Route::get('/leagues/matchDetails/{leagueTeamMatch}', [LeagueController::class, 'showMatchDetails'])->name('leagues.showMatchDetails');
Route::get('/leagues/matchesPoints/{league}', [LeagueController::class, 'matchesPoints'])->name('leagues.matchesPoints');



Route::resource('leagueTeams', LeagueTeamController::class);
Route::resource('leagueTeamPlayers', LeagueTeamPlayerController::class);
Route::resource('leagueRegisteredUsers', LeagueRegisteredUserController::class);
Route::resource('leagueRegisteredGroups', LeagueRegisteredGroupController::class);
Route::resource('leagueGroups', LeagueGroupController::class);
//additional routes for league groups
Route::get('/leagueGroups/showFinancial/{leagueGroup}', [LeagueGroupController::class, 'showFinancial'])->name('leagueGroups.showFinancial');
Route::get('/leagueGroups/createMatches/{leagueGroup}', [LeagueGroupController::class, 'createMatches'])->name('leagueGroups.createMatches');
Route::get('/leagueGroups/matchesSchedule/{leagueGroup}', [LeagueGroupController::class, 'matchesSchedule'])->name('leagueGroups.matchesSchedule');
Route::get('/leagueGroups/matchDetails/{leagueGroupTeamMatch}', [LeagueGroupController::class, 'showMatchDetails'])->name('leagueGroups.showMatchDetails');
// Route::get('/leagueGroups/createTeam/{id}', [LeagueGroupController::class, 'createTeam'])->name('leagueGroups.createTeam');
Route::get('/leagueGroups/matchesPoints/{leagueGroup}', [LeagueGroupController::class, 'matchesPoints'])->name('leagueGroups.matchesPoints');

Route::resource('leagueGroupNames', LeagueGroupNameController::class);
Route::resource('leagueGroupTeams', LeagueGroupTeamController::class);
Route::resource('leagueGroupTeamPlayers', LeagueGroupTeamPlayerController::class);
Route::resource('leagueGroupRegisteredUsers', LeagueGroupRegisteredUserController::class);
Route::resource('leagueGroupRegisteredGroups', LeagueGroupRegisteredGroupController::class);
Route::resource('leagueMatchSchedules', LeagueMatchScheduleController::class);
Route::resource('leagueMatchPoints', LeagueMatchPointController::class);
Route::resource('leagueGroupMatchSchedules', LeagueGroupMatchScheduleController::class);
Route::resource('leagueGroupMatchPoints', LeagueGroupMatchPointController::class);
Route::resource('users', UserController::class);
Route::resource('groupUsers', GroupUserController::class);
Route::resource('groups', GroupController::class);

//Route::get('getallfootballmatches' ,[ApplicationController::class,'getallfootballmatches' ] ) ;

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
// Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home');
Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'App\Http\Controllers\UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
});

Route::group(['middleware' => 'auth'], function () {
	Route::get('{page}', ['as' => 'page.index', 'uses' => 'App\Http\Controllers\PageController@index']);
});

app/Models/LeagueTeamPlayer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\Pivot;

class LeagueTeamPlayer extends Pivot
{
    use HasFactory;
    protected $table = 'league_team_players';

    protected $fillable = ['user_id', 'league_team_id'];

    public function league_team()
    {
        return $this->belongTo('App\Models\LeagueTeam');
    }
    public function user()
    {
        return $this->belongTo('App\Models\User');
    }
}

app/Http/Controllers/LeagueTeamPlayerController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\LeagueTeamPlayerStoreRequest;
use Illuminate\Http\Request;
use App\Models\LeagueTeam;
use App\Models\LeagueTeamPlayer;
use Illuminate\Support\Arr;

class LeagueTeamPlayerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $leagueTeam = LeagueTeam::where('id', request()->league_team_id)->first();
        $league = $leagueTeam->league;
        $usersIds = array();
        //    $test = $leagueTeam->league->with('league_teams.league_team_players')->get();
        //  $test->first()->league_teams->first()->league_team_players;
        foreach ($league->league_teams as $checkTeam) {
            foreach ($checkTeam->league_team_players as $user) {
                $usersIds[] = $user->id;
            }
        }
       
        return view('admin.leagueTeamPlayers.create', compact('leagueTeam'))
            ->with('usersIds', $usersIds);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(LeagueTeamPlayerStoreRequest $request)
    {

        $vaildated = $request->validated();

        foreach ($request->users as $user) {
            $leagueTeamPlayer = new LeagueTeamPlayer;
            $leagueTeamPlayer->league_team_id = $request->league_team_id;
            $leagueTeamPlayer->user_id = $user;
            $leagueTeamPlayer->save();
        }

        return redirect()->back()
            ->with('success', 'تم اضافة اللاعبين بنجاح ');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(LeagueTeamPlayer $leagueTeamPlayer)
    {
        $leagueTeamPlayer->delete();
        return redirect()->back()
            ->with('delete', 'تم حذف اللاعب بنجاح ');
    }
}

resources/views/admin/leagueTeamPlayers/create.blade.php
@extends('layouts.app', [
'class' => '',
'elementActive' => 'leagues'
])

<style>
    p {
        margin: 0 !important;
    }

</style>

@section('content')

    <div class="content">

        @if ($message = Session::get('success'))
            <div class="alert alert-success text-right">
                <p>{{ $message }}</p>
            </div>
        @endif
        @if ($message = Session::get('updated'))
            <div class="alert alert-warning text-right">
                <p>{{ $message }}</p>
            </div>
        @endif
        @if ($message = Session::get('delete'))
            <div class="alert alert-danger text-right">
                <p>{{ $message }}</p>
            </div>
        @endif

        <div class="card">
            <div class="card-header">
                <div class="pull-right">
                    <h5 class="title">{{ __('أضف لاعبين') }}</h5>
                </div>
                <div class="pull-left">
                    <a class="btn btn-primary" href="{{ route('leagues.show', $leagueTeam->league->id) }}"> العودة</a>
                </div>
            </div>
            @if ($errors->any())
                <div class="alert alert-danger text-right">
                    <strong>عذرًا! بعض المدخلات غير صحيحة</strong><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            
            @if ($leagueTeam->league_team_players->count() == $leagueTeam->league->team_players_number)
                <div class="row text-right m-5">
                    <div class="col-md-12">
                        <div class="alert alert-info">
                            <span>عدد اللاعبين مكتمل. لايمكن إضافة المزيد من اللاعبين الى الفريق.</span>
                        </div>
                    
                    </div>
                </div>
            @else
            <form class="col-md-12" action="{{ route('leagueTeamPlayers.store') }}" method="POST"
            enctype="multipart/form-data">
            @csrf
            <div class="card-body">
                <div class="form-row text-right">
                    <div class="form-group col-md-12">
                        <label>{{ __('اسم الفريق') }}</label>
                        <input value="{{ $leagueTeam->name_ar }}" disabled type="text" class="form-control">
                        <input value="{{ $leagueTeam->id }}" type="hidden" name="league_team_id"
                            class="form-control">
                    </div>

                    <div class="form-group col-md-12">
                        <label>{{ __('اللاعبين المسجلين كأفراد') }}</label><br />

                        @foreach ($leagueTeam->league->league_registered_users as $user)
                            @if (!in_array($user->id, $usersIds))
                                <input type="checkbox" name="users[]" value="{{ $user->id }}">
                                {{ $user->name }} {{ $user->position }} <br />
                            @endif
                        @endforeach
                    </div>

                    <div class="form-group col-md-12">
                        <label>{{ __('اللاعبين المسجلين كمجموعات') }}</label><br />
                        @foreach ($leagueTeam->league->groups as $group)
                            @php
                                $groupUsersIds = [];
                                $groupUsersIds[] = $group->user->id;
                                foreach ($group->group_users as $group_user) {
                                    $groupUsersIds[] = $group_user->id;
                                }
                                $arrDiff = array_diff($groupUsersIds, $usersIds);
                                
                            @endphp

                            @if (count($arrDiff) !== 0)
                                <p>{{ $loop->iteration }}-
                                    <strong>اسم المجموعة: {{ $group->name }}</strong>
                                </p>
                            @endif

                            @if (!in_array($group->user->id, $usersIds))
                                <input type="checkbox" name="users[]" value="{{ $group->user->id }}">
                                {{ $group->user->name }}<br />
                            @endif


                            @foreach ($group->group_users as $group_user)
                                @if (!in_array($group_user->id, $usersIds))
                                    <input type="checkbox" name="users[]" value="{{ $group_user->id }}">
                                    {{ $group_user->name }} <br />
                                @endif
                            @endforeach
                        @endforeach
                    </div>

                </div>
            </div>
            <div class="card-footer ">
                <div class="row">
                    <div class="col-md-12 text-center">
                        <button type="submit" class="btn btn-info btn-round">{{ __('أضف اللاعبين') }}</button>
                    </div>
                </div>
            </div>
        </form>
            @endif

       
        </div>

    </div>




@endsection
@push('scripts')
    <script>
        var loadFile = function(event) {
            var image = document.getElementById('output');
            image.src = URL.createObjectURL(event.target.files[0]);
        };
    </script>
@endpush