routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\UserController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\CityController;
use App\Http\Controllers\FootballFieldController;
use App\Http\Controllers\FootballMatchController;
use App\Http\Controllers\LeagueController;
use App\Http\Controllers\LeagueTeamController;
use App\Http\Controllers\LeagueTeamPlayerController;
use App\Http\Controllers\LeagueRegisteredUserController;
use App\Http\Controllers\LeagueRegisteredGroupController;
use App\Http\Controllers\LeagueGroupController;
use App\Http\Controllers\LeagueGroupNameController;
use App\Http\Controllers\LeagueGroupTeamController;
use App\Http\Controllers\LeagueGroupTeamPlayerController;
use App\Http\Controllers\LeagueGroupRegisteredUserController;
use App\Http\Controllers\LeagueGroupRegisteredGroupController;
use App\Http\Controllers\LeagueMatchScheduleController;
use App\Http\Controllers\LeagueMatchPointController;
<<<<<<< HEAD
use App\Http\Controllers\ApplicationController;

=======
use App\Http\Controllers\LeagueGroupMatchScheduleController;
use App\Http\Controllers\LeagueGroupMatchPointController;
use App\Http\Controllers\GroupUserController;
use App\Http\Controllers\GroupController;
>>>>>>> f14405817e86cad95dce38ffcee9e2435b951a9d
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('welcome');
});
Auth::routes();
Route::resource('contacts', 'App\Http\Controllers\ContactController');
Route::resource('products', ProductController::class);
Route::resource('countries', CountryController::class);
Route::resource('cities', CityController::class);
Route::resource('footballFields', FootballFieldController::class);
Route::resource('footballMatches', FootballMatchController::class);
Route::resource('leagues', LeagueController::class);
//additional routes for leagues
Route::get('/leagues/createTeam/{id}', [LeagueController::class, 'createTeam'])->name('leagues.createTeam');
Route::get('/leagues/showFinancial/{league}', [LeagueController::class, 'showFinancial'])->name('leagues.showFinancial');
Route::get('/leagues/createMatches/{league}', [LeagueController::class, 'createMatches'])->name('leagues.createMatches');
Route::get('/leagues/matchesSchedule/{league}', [LeagueController::class, 'matchesSchedule'])->name('leagues.matchesSchedule');
Route::get('/leagues/matchDetails/{leagueTeamMatch}', [LeagueController::class, 'showMatchDetails'])->name('leagues.showMatchDetails');
Route::get('/leagues/matchesPoints/{league}', [LeagueController::class, 'matchesPoints'])->name('leagues.matchesPoints');



Route::resource('leagueTeams', LeagueTeamController::class);
Route::resource('leagueTeamPlayers', LeagueTeamPlayerController::class);
Route::resource('leagueRegisteredUsers', LeagueRegisteredUserController::class);
Route::resource('leagueRegisteredGroups', LeagueRegisteredGroupController::class);
Route::resource('leagueGroups', LeagueGroupController::class);
//additional routes for league groups
Route::get('/leagueGroups/showFinancial/{leagueGroup}', [LeagueGroupController::class, 'showFinancial'])->name('leagueGroups.showFinancial');
Route::get('/leagueGroups/createMatches/{leagueGroup}', [LeagueGroupController::class, 'createMatches'])->name('leagueGroups.createMatches');
Route::get('/leagueGroups/matchesSchedule/{leagueGroup}', [LeagueGroupController::class, 'matchesSchedule'])->name('leagueGroups.matchesSchedule');
Route::get('/leagueGroups/matchDetails/{leagueGroupTeamMatch}', [LeagueGroupController::class, 'showMatchDetails'])->name('leagueGroups.showMatchDetails');
// Route::get('/leagueGroups/createTeam/{id}', [LeagueGroupController::class, 'createTeam'])->name('leagueGroups.createTeam');
Route::get('/leagueGroups/matchesPoints/{leagueGroup}', [LeagueGroupController::class, 'matchesPoints'])->name('leagueGroups.matchesPoints');

Route::resource('leagueGroupNames', LeagueGroupNameController::class);
Route::resource('leagueGroupTeams', LeagueGroupTeamController::class);
Route::resource('leagueGroupTeamPlayers', LeagueGroupTeamPlayerController::class);
Route::resource('leagueGroupRegisteredUsers', LeagueGroupRegisteredUserController::class);
Route::resource('leagueGroupRegisteredGroups', LeagueGroupRegisteredGroupController::class);
Route::resource('leagueMatchSchedules', LeagueMatchScheduleController::class);
Route::resource('leagueMatchPoints', LeagueMatchPointController::class);
Route::resource('leagueGroupMatchSchedules', LeagueGroupMatchScheduleController::class);
Route::resource('leagueGroupMatchPoints', LeagueGroupMatchPointController::class);
Route::resource('users', UserController::class);
Route::resource('groupUsers', GroupUserController::class);
Route::resource('groups', GroupController::class);

//Route::get('getallfootballmatches' ,[ApplicationController::class,'getallfootballmatches' ] ) ;

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
// Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home');
Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'App\Http\Controllers\UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
});

Route::group(['middleware' => 'auth'], function () {
	Route::get('{page}', ['as' => 'page.index', 'uses' => 'App\Http\Controllers\PageController@index']);
});

app/Models/LeagueTeam.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class LeagueTeam extends Model
{
    use HasFactory;
    protected $fillable = ['name', 'name_ar', 'flag_icon', 'league_id'];


    public function league()
    {
        return $this->belongsTo('App\Models\League');
    }

    //users in this team
    public function league_team_players()
    {
        return $this->belongsToMany('App\Models\User', 'league_team_players')
            ->withPivot('id','user_id', 'league_team_id', 'created_at', 'updated_at');
    }

    public function league_team_matches1()
    {
        return $this->hasMany('App\Models\LeagueTeamMatch', 'league_team1_id');
    }
    public function league_team_matches2()
    {
        return $this->hasMany('App\Models\LeagueTeamMatch', 'league_team2_id');
    }
}

app/Http/Controllers/LeagueTeamController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\LeagueTeamStoreRequest;
use App\Http\Requests\LeagueTeamUpdateRequest;
use App\Models\League;
use App\Models\LeagueGroupTeam;
use Illuminate\Http\Request;
use App\Models\LeagueTeam;
use Illuminate\Support\Facades\File;

class LeagueTeamController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $search = request()->query('search');

        if ($search) {
            $leagueTeams = LeagueTeam::whereHas('league', function ($query) use ($search) {
                $query->where('name', 'LIKE', '%' . $search . '%')
                    ->orWhere('name_ar', 'LIKE', '%' . $search . '%');
            })->orWhere('name', 'LIKE', '%' . $search . '%')
                ->orWhere('name_ar', 'LIKE', '%' . $search . '%')
                ->latest()->paginate(5);
            return view('admin.leagueTeams.index', compact('leagueTeams'))
                ->with('i', (request()->input('page', 1) - 1) * 5)->with('search', $search);
        } else {
            $search = null;
            $leagueTeams = LeagueTeam::latest()->paginate(5);
            return view('admin.leagueTeams.index', compact('leagueTeams'))
                ->with('i', (request()->input('page', 1) - 1) * 5)->with('search', $search);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $leagueSelected = request()->league_id ? League::where('id',request()->league_id)->first() : null;
        $leagues = League::latest()->get();
        return view('admin.leagueTeams.create', compact('leagues'))
        ->with('leagueSelected',$leagueSelected);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(LeagueTeamStoreRequest $request)
    {
        $validated = $request->validated();

        $input = $request->all();

        if ($image = $request->file('flag_icon')) {
            $destinationPath = 'storage/images/leagueTeams/';
            $profileImage = date('YmdHis') . "-" .  $image->getClientOriginalName() . "." . $image->getClientOriginalExtension();
            $image->move($destinationPath, $profileImage);
            $input['flag_icon'] = "$profileImage";
        }

        LeagueTeam::create($input);

        return redirect()->route('leagueTeams.index')
            ->with('success', 'تم اضافة الفريق بنجاح ');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(LeagueTeam $leagueTeam)
    {
        return view('admin.leagueTeams.show', compact('leagueTeam'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(LeagueGroupTeam $leagueGroupTeam)
    {
        $leagues = League::latest()->get();
        return view('admin.leagueTeams.edit', compact('leagueTeam'))
            ->with('leagues', $leagues);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(LeagueTeamUpdateRequest $request, LeagueTeam $leagueTeam)
    {
        $validated = $request->validated();

        $input = $request->all();

        if ($image = $request->file('flag_icon')) {
            $destinationPath = 'storage/images/leagueTeams/';
            $profileImage = date('YmdHis') . "-" .  $image->getClientOriginalName() . "." . $image->getClientOriginalExtension();
            $image->move($destinationPath, $profileImage);
            $input['flag_icon'] = "$profileImage";
            if (File::exists(public_path('storage/images/leagueTeams/' . $leagueTeam->flag_icon))) {
                File::delete(public_path('storage/images/leagueTeams/' . $leagueTeam->flag_icon));
            }
        } else {
            $input['flag_icon'] = "$leagueTeam->flag_icon";
        }



        $leagueTeam->update($input);

        return redirect()->route('leagueTeams.index')
            ->with('success', 'تم تعديل الفريق بنجاح ');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(LeagueTeam $leagueTeam)
    {
        if (File::exists(public_path('storage/images/leagueTeams/' . $leagueTeam->flag_icon))) {
            File::delete(public_path('storage/images/leagueTeams/' . $leagueTeam->flag_icon));
        }
        $leagueTeam->delete();
        return redirect()->back()
            ->with('delete', 'تم حذف الدوري بنجاح ');
    }
}

resources/views/admin/leagueTeams/create.blade.php
@extends('layouts.app', [
'class' => '',
'elementActive' => 'leagueTeams'
])
@section('content')

    <div class="content">

        <div class="card">
            <div class="card-header">
                <div class="pull-right">
                    <h5 class="title">{{ __('أضف فريق جديد') }}</h5>
                </div>
                <div class="pull-left">
                    <a class="btn btn-primary" href="{{ route('leagueTeams.index') }}"> العودة</a>
                </div>
            </div>
            @if ($errors->any())
                <div class="alert alert-danger text-right">
                    <strong>عذرًا! بعض المدخلات غير صحيحة</strong><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif


            <form class="col-md-12" action="{{ route('leagueTeams.store') }}" method="POST"
                enctype="multipart/form-data">
                @csrf
                <div class="card-body">
                    <div class="form-row text-right">
                        <div class="form-group col-md-12">
                            <label>{{ __('الدوري') }}</label>

                            @if ($leagueSelected !== null)
                                <input value="{{ $leagueSelected->id }}" type="hidden" name="league_id"
                                    class="form-control">
                                <input placeholder="{{ $leagueSelected->name_ar }} - {{ $leagueSelected->name }} "
                                    type="text" disabled name="name" class="form-control">
                            @else
                                <select name="league_id" class="custom-select">
                                    @foreach ($leagues as $league)
                                        <option value={{ $league->id }}>{{ $league->name_ar }} -
                                            {{ $league->name }}
                                        </option>
                                    @endforeach
                                </select>
                            @endif

                        </div>
                        <div class="form-group col-md-12">
                            <label>{{ __('اسم الفريق بالانجليزي') }}</label>
                            <input placeholder="Real Madrid" type="text" name="name" class="form-control">

                        </div>
                        <div class="form-group col-md-12">
                            <label>{{ __('اسم الفريق بالعربي') }}</label>
                            <input placeholder="ريال مدريد" type="text" name="name_ar" class="form-control">

                        </div>
                        <div class="form-group col-md-12">
                            <label for="file" style="cursor: pointer;">{{ __('اختر صورة العلم') }} <br> <i
                                    style="font-size:40px" class="nc-icon nc-image"></i>
                            </label>
                            <input type="file" accept="image/*" name="flag_icon" id="file" onchange="loadFile(event)"
                                style="display: none;">
                            <img id="output" width="200" />

                        </div>
                    </div>
                </div>
                <div class="card-footer ">
                    <div class="row">
                        <div class="col-md-12 text-center">
                            <button type="submit" class="btn btn-info btn-round">{{ __('أضف الفريق') }}</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>

    </div>




@endsection
@push('scripts')
    <script>
        var loadFile = function(event) {
            var image = document.getElementById('output');
            image.src = URL.createObjectURL(event.target.files[0]);
        };
    </script>
@endpush

resources/views/admin/leagueTeams/edit.blade.php
@extends('layouts.app', [
'class' => '',
'elementActive' => 'leagueTeams'
])
@section('content')

    <div class="content">

        <div class="card">
            <div class="card-header">
                <div class="pull-right">
                    <h5 class="title">{{ __('تعديل بيانات الفريق') }}</h5>
                </div>
                <div class="pull-left">
                    <a class="btn btn-primary" href="{{ route('leagueTeams.index') }}"> العودة</a>
                </div>
            </div>
            @if ($errors->any())
                <div class="alert alert-danger text-right">
                    <strong>عذرًا! بعض المدخلات غير صحيحة</strong><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif


            <form class="col-md-12" action="{{ route('leagueTeams.update', $leagueTeam->id) }}" method="POST"
                enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="card-body">
                    <div class="form-row text-right">
                        <div class="form-group col-md-12">
                            <label>{{ __('الدوري') }}</label>
                            <select name="league_id" class="custom-select">
                                @foreach ($leagues as $league)
                                    <option value={{ $league->id }}>{{ $league->name_ar }} -
                                        {{ $league->name }}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group col-md-12">
                            <label>{{ __('اسم الفريق بالانجليزي') }}</label>
                            <input value="{{ $leagueTeam->name }}" type="text" name="name" class="form-control">

                        </div>
                        <div class="form-group col-md-12">
                            <label>{{ __('اسم الفريق بالعربي') }}</label>
                            <input value="{{ $leagueTeam->name_ar }}" type="text" name="name_ar" class="form-control">

                        </div>
                        <div class="form-group col-md-12">
                            <label>{{ __(' الصورة السابقة') }} <br> <i style="font-size:40px"
                                    class="nc-icon nc-image"></i>
                            </label>
                            <img src="{{ asset('storage/images/leagueTeams/' . $leagueTeam->flag_icon) }}" width="200px">

                        </div>
                        <div class="form-group col-md-12">
                            <label for="file" style="cursor: pointer;">{{ __('اختر صورة العلم') }} <br> <i
                                    style="font-size:40px" class="nc-icon nc-image"></i>
                            </label>
                            <input type="file" accept="image/*" name="flag_icon" id="file" onchange="loadFile(event)"
                                style="display: none;">
                            <img id="output" width="200" />

                        </div>
                    </div>
                </div>
                <div class="card-footer ">
                    <div class="row">
                        <div class="col-md-12 text-center">
                            <button type="submit" class="btn btn-info btn-round">{{ __('تعديل البيانات') }}</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>

    </div>




@endsection
@push('scripts')
    <script>
        var loadFile = function(event) {
            var image = document.getElementById('output');
            image.src = URL.createObjectURL(event.target.files[0]);
        };
    </script>
@endpush

resources/views/admin/leagueTeams/index.blade.php
@extends('layouts.app', [
'class' => '',
'elementActive' => 'leagueTeams'
])

<style>
    .table-responsive {
        overflow: hidden !important;
    }

</style>
@section('content')
    <div class="content">
        @if ($message = Session::get('success'))
            <div class="alert alert-success text-right">
                <p>{{ $message }}</p>
            </div>
        @endif
        @if ($message = Session::get('updated'))
            <div class="alert alert-warning text-right">
                <p>{{ $message }}</p>
            </div>
        @endif
        @if ($message = Session::get('delete'))
            <div class="alert alert-danger text-right">
                <p>{{ $message }}</p>
            </div>
        @endif

        <div class="card">
            <div class="pull-right" style="padding-left:10px">
                <a class="btn btn-success" href="{{ route('leagueTeams.create') }}"> إضافة فريق جديد</a>
            </div>


            <div class="card-header text-right">
                <h4 class="card-title"> قائمة الفرق</h4>
            </div>

            <div class="row mx-3">
                <form method="GET" action="{{ route('leagueTeams.index') }}">
                    <div class="input-group no-border">
                        <input type="text" value="" class="form-control" value="{{ request()->query('search') }}"
                            name="search" placeholder="البحث...">
                        {{-- <div class="input-group-append">
                                <div class="input-group-text">
                                    <i class="nc-icon nc-zoom-split"></i>
                                </div>
                            </div> --}}
                        <button type="submit" class="btn btn-info btn-icon">البحث</button>

                    </div>
                </form>
            </div>
            <div class="card-body">
                @if (count($leagueTeams) > 0)
                    <div class="table-responsive text-right">
                        <table class="table">
                            <thead class=" text-primary">
                                <th>الرقم</th>
                                <th>اسم الدوري</th>
                                <th>اسم الفريق بالانجليزي</th>
                                <th>اسم الفريق بالعربي</th>
                                <th>علم الفريق</th>
                                <th>عدد اللاعبين</th>
                                <th>الإجراءات</th>
                            </thead>
                            <tbody>


                                @foreach ($leagueTeams as $leagueTeam)
                                    <tr>
                                        <td>{{ ++$i }}</td>
                                        <td>{{ $leagueTeam->league->name_ar }}</td>
                                        <td>{{ $leagueTeam->name }}</td>
                                        <td>{{ $leagueTeam->name_ar }}</td>
                                        <td>
                                            <img width="80" height="80"
                                                src="{{ asset('storage/images/leagueTeams/' . $leagueTeam->flag_icon) }}">
                                        </td>
                                        <td>
                                            {{ $leagueTeam->league->team_players_number }} /
                                            {{ $leagueTeam->league_team_players->count() }}
                                        </td>
                                        <td>
                                            <form action="{{ route('leagueTeams.destroy', $leagueTeam->id) }}"
                                                method="POST">
                                                <a class="btn btn-info btn-icon  "
                                                    href="{{ route('leagueTeams.show', $leagueTeam->id) }}"> <i
                                                        class="fa fa-eye"></i></a>
                                                <a class="btn btn-primary btn-icon"
                                                    href="{{ route('leagueTeams.edit', $leagueTeam->id) }}"><i
                                                        class="fa fa-edit"></i></a>

                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-danger btn-icon"><i
                                                        class="fa fa-times"></i></button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                @else
                    @if ($search)
                        <div class="row">
                            <div class="col-12">
                                <div class="text-center">
                                    <h6>لا يوجد نتائج مطابقة لعملية البحث "{{ $search }}"</h6>
                                </div>
                            </div>
                        </div>
                    @else
                        <div class="row">
                            <div class="col-12">
                                <div class="text-center">
                                    <h6>لم يتم إدخال البيانات بعد</h6>
                                </div>
                            </div>
                        </div>
                    @endif
                @endif
            </div>

        </div>
        <div>
            {{-- {!! $products->links('vendor.pagination.simple-tailwind') !!} --}}
            {!! $leagueTeams->appends(['search' => request()->query('search')])->links('vendor.pagination.bootstrap-4') !!}
        </div>
    </div>
@endsection

resources/views/admin/leagueTeams/show.blade.php
@extends('layouts.app', [
'class' => '',
'elementActive' => 'leagueTeams'
])

<style>
    p {
        margin: 0 !important;
    }

    .table-responsive {
        overflow: hidden !important;
    }

</style>
@section('content')
    <div class="content">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-12 margin-tb">
                        <div class="pull-right">
                            <h2> عرض الفريق</h2>
                        </div>
                        <div class="pull-left">
                            <a class="btn btn-primary" href="{{ route('leagueTeams.index') }}"> العودة</a>
                        </div>
                    </div>
                </div>

                <div class="row text-right">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>الدوري: </strong>
                            {{ $leagueTeam->league->name_ar }}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>الاسم بالانجليزي: </strong>
                            {{ $leagueTeam->name }}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>الاسم بالعربي: </strong>
                            {{ $leagueTeam->name_ar }}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>صورة العرض: </strong>
                            <img src="{{ asset('storage/images/leagueTeams/' . $leagueTeam->flag_icon) }}" width="80"
                                height="80">
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>عدد اللاعبين: </strong>
                            {{ $leagueTeam->league->team_players_number }} /
                            {{ $leagueTeam->league_team_players->count() }}
                        </div>
                    </div>
                    {{-- <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>اسماء اللاعبين: </strong>
                            @foreach ($leagueTeam->league_team_players as $user)
                                <p>
                                    {{ $user->name }}
                                </p>
                            @endforeach
                        </div>
                    </div> --}}
                </div>

                <div class="table-responsive text-right">
                    <table class="table">
                        <thead class=" text-primary">
                            <th>الرقم</th>
                            <th>اسماء اللاعبين</th>
                            <th>الإجراءات</th>
                        </thead>
                        <tbody>


                            @foreach ($leagueTeam->league_team_players as $user)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $user->name }}</td>
                                    <td>
                                        <form action="{{ route('leagueTeamPlayers.destroy', $user->pivot->id) }}" method="POST">
                                            {{-- <a class="btn btn-info btn-icon  "
                                                href="{{ route('leagues.show', $user->id) }}"> <i
                                                    class="fa fa-eye"></i></a>
                                            <a class="btn btn-primary btn-icon"
                                                href="{{ route('leagues.edit', $user->id) }}"><i
                                                    class="fa fa-edit"></i></a> --}}

                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger btn-icon"><i
                                                    class="fa fa-times"></i></button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
@endsection