routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\UserController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\CityController;
use App\Http\Controllers\FootballFieldController;
use App\Http\Controllers\FootballMatchController;
use App\Http\Controllers\LeagueController;
use App\Http\Controllers\LeagueTeamController;
use App\Http\Controllers\LeagueTeamPlayerController;
use App\Http\Controllers\LeagueRegisteredUserController;
use App\Http\Controllers\LeagueRegisteredGroupController;
use App\Http\Controllers\LeagueGroupController;
use App\Http\Controllers\LeagueGroupNameController;
use App\Http\Controllers\LeagueGroupTeamController;
use App\Http\Controllers\LeagueGroupTeamPlayerController;
use App\Http\Controllers\LeagueGroupRegisteredUserController;
use App\Http\Controllers\LeagueGroupRegisteredGroupController;
use App\Http\Controllers\LeagueMatchScheduleController;
use App\Http\Controllers\LeagueMatchPointController;
<<<<<<< HEAD
use App\Http\Controllers\ApplicationController;

=======
use App\Http\Controllers\LeagueGroupMatchScheduleController;
use App\Http\Controllers\LeagueGroupMatchPointController;
use App\Http\Controllers\GroupUserController;
use App\Http\Controllers\GroupController;
>>>>>>> f14405817e86cad95dce38ffcee9e2435b951a9d
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('welcome');
});
Auth::routes();
Route::resource('contacts', 'App\Http\Controllers\ContactController');
Route::resource('products', ProductController::class);
Route::resource('countries', CountryController::class);
Route::resource('cities', CityController::class);
Route::resource('footballFields', FootballFieldController::class);
Route::resource('footballMatches', FootballMatchController::class);
Route::resource('leagues', LeagueController::class);
//additional routes for leagues
Route::get('/leagues/createTeam/{id}', [LeagueController::class, 'createTeam'])->name('leagues.createTeam');
Route::get('/leagues/showFinancial/{league}', [LeagueController::class, 'showFinancial'])->name('leagues.showFinancial');
Route::get('/leagues/createMatches/{league}', [LeagueController::class, 'createMatches'])->name('leagues.createMatches');
Route::get('/leagues/matchesSchedule/{league}', [LeagueController::class, 'matchesSchedule'])->name('leagues.matchesSchedule');
Route::get('/leagues/matchDetails/{leagueTeamMatch}', [LeagueController::class, 'showMatchDetails'])->name('leagues.showMatchDetails');
Route::get('/leagues/matchesPoints/{league}', [LeagueController::class, 'matchesPoints'])->name('leagues.matchesPoints');



Route::resource('leagueTeams', LeagueTeamController::class);
Route::resource('leagueTeamPlayers', LeagueTeamPlayerController::class);
Route::resource('leagueRegisteredUsers', LeagueRegisteredUserController::class);
Route::resource('leagueRegisteredGroups', LeagueRegisteredGroupController::class);
Route::resource('leagueGroups', LeagueGroupController::class);
//additional routes for league groups
Route::get('/leagueGroups/showFinancial/{leagueGroup}', [LeagueGroupController::class, 'showFinancial'])->name('leagueGroups.showFinancial');
Route::get('/leagueGroups/createMatches/{leagueGroup}', [LeagueGroupController::class, 'createMatches'])->name('leagueGroups.createMatches');
Route::get('/leagueGroups/matchesSchedule/{leagueGroup}', [LeagueGroupController::class, 'matchesSchedule'])->name('leagueGroups.matchesSchedule');
Route::get('/leagueGroups/matchDetails/{leagueGroupTeamMatch}', [LeagueGroupController::class, 'showMatchDetails'])->name('leagueGroups.showMatchDetails');
// Route::get('/leagueGroups/createTeam/{id}', [LeagueGroupController::class, 'createTeam'])->name('leagueGroups.createTeam');
Route::get('/leagueGroups/matchesPoints/{leagueGroup}', [LeagueGroupController::class, 'matchesPoints'])->name('leagueGroups.matchesPoints');

Route::resource('leagueGroupNames', LeagueGroupNameController::class);
Route::resource('leagueGroupTeams', LeagueGroupTeamController::class);
Route::resource('leagueGroupTeamPlayers', LeagueGroupTeamPlayerController::class);
Route::resource('leagueGroupRegisteredUsers', LeagueGroupRegisteredUserController::class);
Route::resource('leagueGroupRegisteredGroups', LeagueGroupRegisteredGroupController::class);
Route::resource('leagueMatchSchedules', LeagueMatchScheduleController::class);
Route::resource('leagueMatchPoints', LeagueMatchPointController::class);
Route::resource('leagueGroupMatchSchedules', LeagueGroupMatchScheduleController::class);
Route::resource('leagueGroupMatchPoints', LeagueGroupMatchPointController::class);
Route::resource('users', UserController::class);
Route::resource('groupUsers', GroupUserController::class);
Route::resource('groups', GroupController::class);

//Route::get('getallfootballmatches' ,[ApplicationController::class,'getallfootballmatches' ] ) ;

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
// Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home');
Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'App\Http\Controllers\UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
});

Route::group(['middleware' => 'auth'], function () {
	Route::get('{page}', ['as' => 'page.index', 'uses' => 'App\Http\Controllers\PageController@index']);
});

app/Models/LeagueGroupMatchSchedule.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class LeagueGroupMatchSchedule extends Model
{
    use HasFactory;
    protected $fillable = ['time', 'date', 'league_group_team_match_id'];

    public function league_group_team_match()
    {
        return $this->belongsTo('App\Models\LeagueGroupTeamMatch');
    }
}

app/Http/Controllers/LeagueGroupMatchScheduleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\LeagueGroupMatchScheduleStoreRequest;
use App\Models\LeagueGroupMatchSchedule;
use App\Models\LeagueGroupTeamMatch;
use Illuminate\Http\Request;

class LeagueGroupMatchScheduleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $leagueGroupTeamMatchId =  request()->league_group_team_match_id;
        $leagueGroupTeamMatch = LeagueGroupTeamMatch::where('id', $leagueGroupTeamMatchId)->first();
        return view('admin.leagueGroupMatchSchedules.create', compact('leagueGroupTeamMatchId'))
            ->with('leagueGroupTeamMatch', $leagueGroupTeamMatch);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(LeagueGroupMatchScheduleStoreRequest $request)
    {
        $validated = $request->validated();

        LeagueGroupMatchSchedule::create($request->all());

        $leagueGroupTeamMatch = LeagueGroupTeamMatch::where('id', $request->league_group_team_match_id)->first();

        return redirect('/leagueGroups/matchesSchedule/' . $leagueGroupTeamMatch->league_group_team1->league_group_name->league_group_id)
            ->with('success', 'تم اضافة الموعد بنجاح ');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(LeagueGroupMatchSchedule $leagueGroupMatchSchedule)
    {
        $leagueGroupMatchSchedule->delete();
        return redirect()->back()
            ->with('delete', 'تم حذف موعد المباراة بنجاح ');
    }
}

resources/views/admin/leagueGroupMatchSchedules/create.blade.php
@extends('layouts.app', [
'class' => '',
'elementActive' => 'leagueGroups'
])


@section('content')
<style>
 /* #mydate{
    -webkit-transform: scaleX(-1);
  transform: scaleX(-1);
 } */
</style>
    <div class="content">

        <div class="card">
            <div class="card-header">
                <div class="pull-right">
                    <h5 class="title">{{ __('أضف موعد للمباراة') }}</h5>
                </div>
                <div class="pull-left">
                    <a class="btn btn-primary" href="{{ url()->previous() }}"> العودة</a>
                </div>
            </div>
            @if ($errors->any())
                <div class="alert alert-danger text-right">
                    <strong>عذرًا! بعض المدخلات غير صحيحة</strong><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif


            @if ($leagueGroupTeamMatch->league_group_match_schedule)
                <div class="row text-right m-5">
                    <div class="col-md-12">
                        <div class="alert alert-info">
                            <span>لا يمكن اضافة موعد للمباراة. هنالك موعد تم ادخاله مسبقاً. الرجاء حذف الموعد وادخال موعد جديد.</span>
                        </div>

                    </div>
                </div>
            @else
                <form class="col-md-12" action="{{ route('leagueGroupMatchSchedules.store') }}" method="POST"
                    enctype="multipart/form-data">
                    @csrf
                    <div class="card-body">
                        <div class="form-row text-right">
                            <div class="form-group col-md-12">
                                <label>{{ __('تاريخ المباراة') }}</label>
                                <input value="{{Carbon\Carbon::now()->format('Y-m-d')}}" placeholder="2022/01/01" type="date" name="date" id="mydate" class="form-control">

                            </div>
                            <div class="form-group col-md-12">
                                <label>{{ __('توقيت المباراة') }}</label>
                                <input placeholder="10:00 AM" type="time" name="time" style="direction: ltr !important" class="form-control">
                                <input type="hidden" value="{{ $leagueGroupTeamMatchId }}"
                                    name="league_group_team_match_id" class="form-control">

                            </div>
                        </div>
                    </div>
                    <div class="card-footer ">
                        <div class="row">
                            <div class="col-md-12 text-center">
                                <button type="submit" class="btn btn-info btn-round">{{ __('أضف الى الجدول') }}</button>
                            </div>
                        </div>
                    </div>
                </form>
             
            @endif


        </div>

    </div>




@endsection